### ISSUE TITLE
Question about the data origin

### ISSUE THREAD

**Issue by schmityv** [jackyko1991/vnet-tensorflow#3]
Hello,

I have a question about the train data that you used. In the quoted paper about the v-net, the authors used MRI-data from the "promise challenge" (https://promise12.grand-challenge.org/). 
Are you testing your implementation with the same data?

Best regards,
Yves

**Comment by mobbSF** [comment]
I had the same question and would be interested in the answer. I suspect that the dataset that jackyko1991 used was the public NifTI dataset but not sure myself.

**Comment by jackyko1991** [comment]
@mobbSF regarding your questions
1. The algo can read .nii, .nii.gz without any code changes, not sure about .hdr/.img analyze format but believe to be readable directly.

2. The dimension is arbitary but it will affect training speed and convergency rate. By default if your image is in RAS direction the last term should be z axis in world coordinate.

3. If you need to read dicom images, you need to modify the reader in NifityDataset.py with following reader: https://simpleitk.readthedocs.io/en/master/Examples/DicomSeriesReader/Documentation.html
JPG/PNG can be assebled to 3D itk images by manually stacking them. Nifti is the best single medical image format as it can preserve spatial information and orientation in it's header.
